import { Container } from 'inversify';
import { Types } from '@/Core/infrastructure/Types';
import { getMultipleImagesQuery } from '@/Core/usecases/getMultipleImages';
import { Fetcher, FetcherI } from '@/Core/infrastructure/Fetcher';
import { SliderPort } from '@/Core/ports/Slider.port';
import { SliderAdapter } from '@/Core/infrastructure/Slider.adapter';
import { SliderService } from '@/Core/services/Slider.service';
import { Axios } from '@/Core/infrastructure/Axios';
import { ProductService } from '@/Core/services/Product.service';
import { ProductAdapter } from '@/Core/infrastructure/Product.adapter';
import { ProductPort } from '@/Core/ports/Product.port';
import { GetProductsQuery } from '@/Core/usecases/getProductsQuery';
import { CookiesAdapter, VueCookiesAdapter } from '@/Core/infrastructure/VueCookies.adapter';

const container = new Container();
container.bind<getMultipleImagesQuery>(Types.getMultipleImagesQuery).to(SliderService);
container.bind<SliderService>(Types.SliderService).to(SliderService);
container.bind<FetcherI>(Types.FetcherI).to(Fetcher);
container.bind<SliderPort>(Types.SliderPort).to(SliderAdapter);
container.bind<SliderAdapter>(Types.SliderAdapter).to(SliderAdapter);
container.bind<Axios>(Types.Axios).to(Axios);
container.bind<VueCookiesAdapter>(Types.VueCookiesAdapter).to(VueCookiesAdapter);
container.bind<ProductService>(Types.ProductService).to(ProductService);
container.bind<GetProductsQuery>(Types.GetProductsQuery).to(ProductService);
container.bind<ProductAdapter>(Types.ProductAdapter).to(ProductAdapter);
container.bind<ProductPort>(Types.ProductPort).to(ProductAdapter);
container.bind<ProductPort>(Types.ProductPort).to(ProductAdapter);
container.bind<CookiesAdapter>(Types.CookiesAdapter).to(VueCookiesAdapter);
export { container };
